// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Admins struct {
	ID        pgtype.UUID        `json:"id"`
	CognitoID string             `json:"cognito_id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Citizens struct {
	ID                pgtype.UUID        `json:"id"`
	CognitoID         string             `json:"cognito_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	Phone             pgtype.Text        `json:"phone"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	DateOfBirth       pgtype.Date        `json:"date_of_birth"`
	Gender            pgtype.Text        `json:"gender"`
	Address           pgtype.Text        `json:"address"`
	CccdNumber        pgtype.Text        `json:"cccd_number"`
	FaceEmbedding     pgvector.Vector    `json:"face_embedding"`
	EmergencyContacts []byte             `json:"emergency_contacts"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmergencyReports struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	VictimID             pgtype.UUID        `json:"victim_id"`
	LocationLat          string             `json:"location_lat"`
	LocationLon          string             `json:"location_lon"`
	SituationDescription pgtype.Text        `json:"situation_description"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MedicalRecords struct {
	CitizenID           pgtype.UUID        `json:"citizen_id"`
	DistinguishingMarks pgtype.Text        `json:"distinguishing_marks"`
	BloodGroup          pgtype.Text        `json:"blood_group"`
	Allergies           []string           `json:"allergies"`
	BackgroundDiseases  []string           `json:"background_diseases"`
	CurrentMedications  []string           `json:"current_medications"`
	Notes               pgtype.Text        `json:"notes"`
	LastUpdated         pgtype.Timestamptz `json:"last_updated"`
}

type NfcTags struct {
	ID           string             `json:"id"`
	Name         pgtype.Text        `json:"name"`
	Status       string             `json:"status"`
	CitizenID    pgtype.UUID        `json:"citizen_id"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
}

type QrCodes struct {
	ID         pgtype.UUID        `json:"id"`
	Name       pgtype.Text        `json:"name"`
	Status     string             `json:"status"`
	CitizenID  pgtype.UUID        `json:"citizen_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Staff struct {
	ID           pgtype.UUID        `json:"id"`
	CognitoID    string             `json:"cognito_id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	HospitalName string             `json:"hospital_name"`
	Department   pgtype.Text        `json:"department"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
