// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCitizen(ctx context.Context, arg CreateCitizenParams) (Citizens, error)
	CreateEmergencyReport(ctx context.Context, arg CreateEmergencyReportParams) (EmergencyReports, error)
	CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (MedicalRecords, error)
	CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCodes, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (HealthcareStaff, error)
	DeleteOTP(ctx context.Context, phone string) error
	GetCitizen(ctx context.Context, id pgtype.UUID) (Citizens, error)
	GetCitizenByCCCD(ctx context.Context, cccdNumber pgtype.Text) (Citizens, error)
	GetCitizenByPhone(ctx context.Context, phone pgtype.Text) (Citizens, error)
	GetCountCitizens(ctx context.Context) (int64, error)
	GetCountEmergencyToday(ctx context.Context) (int64, error)
	GetCountStaff(ctx context.Context) (int64, error)
	GetEmergencyHistory(ctx context.Context, reporterID pgtype.UUID) ([]EmergencyReports, error)
	GetMedicalRecord(ctx context.Context, citizenID pgtype.UUID) (MedicalRecords, error)
	GetNFCTag(ctx context.Context, id string) (NfcTags, error)
	GetOTP(ctx context.Context, phone string) (Otps, error)
	GetQRCode(ctx context.Context, id pgtype.UUID) (QrCodes, error)
	GetStaffByEmail(ctx context.Context, email string) (HealthcareStaff, error)
	RegisterNFCTag(ctx context.Context, arg RegisterNFCTagParams) (NfcTags, error)
	SearchCitizenByFace(ctx context.Context, arg SearchCitizenByFaceParams) ([]SearchCitizenByFaceRow, error)
	UpdateCitizen(ctx context.Context, arg UpdateCitizenParams) (Citizens, error)
	UpdateMedicalRecord(ctx context.Context, arg UpdateMedicalRecordParams) (MedicalRecords, error)
	UpdateNFCLastUsed(ctx context.Context, id string) error
	UpdateNFCTagStatus(ctx context.Context, arg UpdateNFCTagStatusParams) (NfcTags, error)
	UpdateQRLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateQRStatus(ctx context.Context, arg UpdateQRStatusParams) (QrCodes, error)
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error
	UpsertOTP(ctx context.Context, arg UpsertOTPParams) error
}

var _ Querier = (*Queries)(nil)
