// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCitizens = `-- name: CountCitizens :one
SELECT COUNT(*) FROM citizens
`

func (q *Queries) CountCitizens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCitizens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmergencyToday = `-- name: CountEmergencyToday :one
SELECT COUNT(*) FROM emergency_reports
WHERE created_at >= NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountEmergencyToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmergencyToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaff = `-- name: CountStaff :one
SELECT COUNT(*) FROM staff
`

func (q *Queries) CountStaff(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one

INSERT INTO admins (
    cognito_id, email, full_name, avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, cognito_id, email, full_name, avatar_url, created_at, updated_at
`

type CreateAdminParams struct {
	CognitoID string      `json:"cognito_id"`
	Email     string      `json:"email"`
	FullName  string      `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// =============================================
// Admin Queries
// =============================================
func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admins, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.CognitoID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCitizen = `-- name: CreateCitizen :one

INSERT INTO citizens (
    cognito_id, email, full_name, phone, avatar_url
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, cognito_id, email, full_name, phone, avatar_url, date_of_birth, gender, address, cccd_number, face_embedding, emergency_contacts, created_at, updated_at
`

type CreateCitizenParams struct {
	CognitoID string      `json:"cognito_id"`
	Email     string      `json:"email"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// =============================================
// Citizens Queries
// =============================================
func (q *Queries) CreateCitizen(ctx context.Context, arg CreateCitizenParams) (Citizens, error) {
	row := q.db.QueryRow(ctx, createCitizen,
		arg.CognitoID,
		arg.Email,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.CccdNumber,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmergencyReport = `-- name: CreateEmergencyReport :one

INSERT INTO emergency_reports (
    reporter_id, victim_id, location_lat, location_lon, situation_description, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, reporter_id, victim_id, location_lat, location_lon, situation_description, status, created_at, updated_at
`

type CreateEmergencyReportParams struct {
	ReporterID           pgtype.UUID `json:"reporter_id"`
	VictimID             pgtype.UUID `json:"victim_id"`
	LocationLat          string      `json:"location_lat"`
	LocationLon          string      `json:"location_lon"`
	SituationDescription pgtype.Text `json:"situation_description"`
	Status               string      `json:"status"`
}

// =============================================
// Emergency Reports
// =============================================
func (q *Queries) CreateEmergencyReport(ctx context.Context, arg CreateEmergencyReportParams) (EmergencyReports, error) {
	row := q.db.QueryRow(ctx, createEmergencyReport,
		arg.ReporterID,
		arg.VictimID,
		arg.LocationLat,
		arg.LocationLon,
		arg.SituationDescription,
		arg.Status,
	)
	var i EmergencyReports
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VictimID,
		&i.LocationLat,
		&i.LocationLon,
		&i.SituationDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedicalRecord = `-- name: CreateMedicalRecord :one

INSERT INTO medical_records (
    citizen_id, distinguishing_marks, blood_group, allergies,
    background_diseases, current_medications, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated
`

type CreateMedicalRecordParams struct {
	CitizenID           pgtype.UUID `json:"citizen_id"`
	DistinguishingMarks pgtype.Text `json:"distinguishing_marks"`
	BloodGroup          pgtype.Text `json:"blood_group"`
	Allergies           []string    `json:"allergies"`
	BackgroundDiseases  []string    `json:"background_diseases"`
	CurrentMedications  []string    `json:"current_medications"`
	Notes               pgtype.Text `json:"notes"`
}

// =============================================
// Medical Records
// =============================================
func (q *Queries) CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, createMedicalRecord,
		arg.CitizenID,
		arg.DistinguishingMarks,
		arg.BloodGroup,
		arg.Allergies,
		arg.BackgroundDiseases,
		arg.CurrentMedications,
		arg.Notes,
	)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const createNFCTag = `-- name: CreateNFCTag :one

INSERT INTO nfc_tags (id, name, status, citizen_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, status, citizen_id, registered_at, last_used_at
`

type CreateNFCTagParams struct {
	ID        string      `json:"id"`
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	CitizenID pgtype.UUID `json:"citizen_id"`
}

// =============================================
// NFC Tags
// =============================================
func (q *Queries) CreateNFCTag(ctx context.Context, arg CreateNFCTagParams) (NfcTags, error) {
	row := q.db.QueryRow(ctx, createNFCTag,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CitizenID,
	)
	var i NfcTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.RegisteredAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createQRCode = `-- name: CreateQRCode :one

INSERT INTO qr_codes (name, status, citizen_id)
VALUES ($1, $2, $3)
RETURNING id, name, status, citizen_id, created_at, last_used_at
`

type CreateQRCodeParams struct {
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	CitizenID pgtype.UUID `json:"citizen_id"`
}

// =============================================
// QR Codes
// =============================================
func (q *Queries) CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCodes, error) {
	row := q.db.QueryRow(ctx, createQRCode, arg.Name, arg.Status, arg.CitizenID)
	var i QrCodes
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createStaff = `-- name: CreateStaff :one

INSERT INTO staff (
    cognito_id, email, full_name, phone, hospital_name, department, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at
`

type CreateStaffParams struct {
	CognitoID    string      `json:"cognito_id"`
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	HospitalName string      `json:"hospital_name"`
	Department   pgtype.Text `json:"department"`
	Status       string      `json:"status"`
}

// =============================================
// Staff Queries
// =============================================
func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.CognitoID,
		arg.Email,
		arg.FullName,
		arg.Phone,
		arg.HospitalName,
		arg.Department,
		arg.Status,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, cognito_id, email, full_name, avatar_url, created_at, updated_at FROM admins WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdmin(ctx context.Context, id pgtype.UUID) (Admins, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByCognitoID = `-- name: GetAdminByCognitoID :one
SELECT id, cognito_id, email, full_name, avatar_url, created_at, updated_at FROM admins WHERE cognito_id = $1 LIMIT 1
`

func (q *Queries) GetAdminByCognitoID(ctx context.Context, cognitoID string) (Admins, error) {
	row := q.db.QueryRow(ctx, getAdminByCognitoID, cognitoID)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCitizen = `-- name: GetCitizen :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, date_of_birth, gender, address, cccd_number, face_embedding, emergency_contacts, created_at, updated_at FROM citizens WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCitizen(ctx context.Context, id pgtype.UUID) (Citizens, error) {
	row := q.db.QueryRow(ctx, getCitizen, id)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.CccdNumber,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCitizenByCognitoID = `-- name: GetCitizenByCognitoID :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, date_of_birth, gender, address, cccd_number, face_embedding, emergency_contacts, created_at, updated_at FROM citizens WHERE cognito_id = $1 LIMIT 1
`

func (q *Queries) GetCitizenByCognitoID(ctx context.Context, cognitoID string) (Citizens, error) {
	row := q.db.QueryRow(ctx, getCitizenByCognitoID, cognitoID)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.CccdNumber,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCitizenByEmail = `-- name: GetCitizenByEmail :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, date_of_birth, gender, address, cccd_number, face_embedding, emergency_contacts, created_at, updated_at FROM citizens WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCitizenByEmail(ctx context.Context, email string) (Citizens, error) {
	row := q.db.QueryRow(ctx, getCitizenByEmail, email)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.CccdNumber,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyReport = `-- name: GetEmergencyReport :one
SELECT id, reporter_id, victim_id, location_lat, location_lon, situation_description, status, created_at, updated_at FROM emergency_reports WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmergencyReport(ctx context.Context, id pgtype.UUID) (EmergencyReports, error) {
	row := q.db.QueryRow(ctx, getEmergencyReport, id)
	var i EmergencyReports
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VictimID,
		&i.LocationLat,
		&i.LocationLon,
		&i.SituationDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicalRecord = `-- name: GetMedicalRecord :one
SELECT citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated FROM medical_records WHERE citizen_id = $1 LIMIT 1
`

func (q *Queries) GetMedicalRecord(ctx context.Context, citizenID pgtype.UUID) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, getMedicalRecord, citizenID)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const getNFCTag = `-- name: GetNFCTag :one
SELECT id, name, status, citizen_id, registered_at, last_used_at FROM nfc_tags WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNFCTag(ctx context.Context, id string) (NfcTags, error) {
	row := q.db.QueryRow(ctx, getNFCTag, id)
	var i NfcTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.RegisteredAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getQRCode = `-- name: GetQRCode :one
SELECT id, name, status, citizen_id, created_at, last_used_at FROM qr_codes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQRCode(ctx context.Context, id pgtype.UUID) (QrCodes, error) {
	row := q.db.QueryRow(ctx, getQRCode, id)
	var i QrCodes
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getStaff = `-- name: GetStaff :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at FROM staff WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStaff(ctx context.Context, id pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByCognitoID = `-- name: GetStaffByCognitoID :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at FROM staff WHERE cognito_id = $1 LIMIT 1
`

func (q *Queries) GetStaffByCognitoID(ctx context.Context, cognitoID string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByCognitoID, cognitoID)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at FROM staff WHERE email = $1 LIMIT 1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, email)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at FROM staff ORDER BY created_at DESC
`

func (q *Queries) ListStaff(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.CognitoID,
			&i.Email,
			&i.FullName,
			&i.Phone,
			&i.AvatarUrl,
			&i.HospitalName,
			&i.Department,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCitizenByFace = `-- name: SearchCitizenByFace :many
SELECT id, full_name, avatar_url, face_embedding <=> $1 AS distance
FROM citizens
WHERE face_embedding IS NOT NULL
ORDER BY distance ASC
LIMIT $2
`

type SearchCitizenByFaceParams struct {
	FaceEmbedding pgvector.Vector `json:"face_embedding"`
	Limit         int32           `json:"limit"`
}

type SearchCitizenByFaceRow struct {
	ID        pgtype.UUID `json:"id"`
	FullName  string      `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Distance  interface{} `json:"distance"`
}

func (q *Queries) SearchCitizenByFace(ctx context.Context, arg SearchCitizenByFaceParams) ([]SearchCitizenByFaceRow, error) {
	rows, err := q.db.Query(ctx, searchCitizenByFace, arg.FaceEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCitizenByFaceRow
	for rows.Next() {
		var i SearchCitizenByFaceRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.AvatarUrl,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCitizen = `-- name: UpdateCitizen :one
UPDATE citizens
SET
    full_name    = $2,
    phone        = $3,
    avatar_url   = $4,
    date_of_birth = $5,
    gender       = $6,
    address      = $7,
    cccd_number  = $8,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, cognito_id, email, full_name, phone, avatar_url, date_of_birth, gender, address, cccd_number, face_embedding, emergency_contacts, created_at, updated_at
`

type UpdateCitizenParams struct {
	ID          pgtype.UUID `json:"id"`
	FullName    string      `json:"full_name"`
	Phone       pgtype.Text `json:"phone"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      pgtype.Text `json:"gender"`
	Address     pgtype.Text `json:"address"`
	CccdNumber  pgtype.Text `json:"cccd_number"`
}

func (q *Queries) UpdateCitizen(ctx context.Context, arg UpdateCitizenParams) (Citizens, error) {
	row := q.db.QueryRow(ctx, updateCitizen,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.CccdNumber,
	)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.CccdNumber,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCitizenFaceEmbedding = `-- name: UpdateCitizenFaceEmbedding :exec
UPDATE citizens SET face_embedding = $2 WHERE id = $1
`

type UpdateCitizenFaceEmbeddingParams struct {
	ID            pgtype.UUID     `json:"id"`
	FaceEmbedding pgvector.Vector `json:"face_embedding"`
}

func (q *Queries) UpdateCitizenFaceEmbedding(ctx context.Context, arg UpdateCitizenFaceEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateCitizenFaceEmbedding, arg.ID, arg.FaceEmbedding)
	return err
}

const updateMedicalRecord = `-- name: UpdateMedicalRecord :one
UPDATE medical_records
SET
    distinguishing_marks = $2,
    blood_group          = $3,
    allergies            = $4,
    background_diseases  = $5,
    current_medications  = $6,
    notes                = $7,
    last_updated         = NOW()
WHERE citizen_id = $1
RETURNING citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated
`

type UpdateMedicalRecordParams struct {
	CitizenID           pgtype.UUID `json:"citizen_id"`
	DistinguishingMarks pgtype.Text `json:"distinguishing_marks"`
	BloodGroup          pgtype.Text `json:"blood_group"`
	Allergies           []string    `json:"allergies"`
	BackgroundDiseases  []string    `json:"background_diseases"`
	CurrentMedications  []string    `json:"current_medications"`
	Notes               pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateMedicalRecord(ctx context.Context, arg UpdateMedicalRecordParams) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, updateMedicalRecord,
		arg.CitizenID,
		arg.DistinguishingMarks,
		arg.BloodGroup,
		arg.Allergies,
		arg.BackgroundDiseases,
		arg.CurrentMedications,
		arg.Notes,
	)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const updateNFCLastUsed = `-- name: UpdateNFCLastUsed :exec
UPDATE nfc_tags SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateNFCLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateNFCLastUsed, id)
	return err
}

const updateQRLastUsed = `-- name: UpdateQRLastUsed :exec
UPDATE qr_codes SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateQRLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateQRLastUsed, id)
	return err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET
    full_name     = $2,
    phone         = $3,
    avatar_url    = $4,
    hospital_name = $5,
    department    = $6,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at
`

type UpdateStaffParams struct {
	ID           pgtype.UUID `json:"id"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	HospitalName string      `json:"hospital_name"`
	Department   pgtype.Text `json:"department"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.HospitalName,
		arg.Department,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStaffStatus = `-- name: UpdateStaffStatus :one
UPDATE staff SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, cognito_id, email, full_name, phone, avatar_url, hospital_name, department, status, created_at, updated_at
`

type UpdateStaffStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaffStatus, arg.ID, arg.Status)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.CognitoID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.HospitalName,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
