// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createCitizen = `-- name: CreateCitizen :one
INSERT INTO citizens (
    full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts, created_at, updated_at
`

type CreateCitizenParams struct {
	FullName          string          `json:"full_name"`
	DateOfBirth       pgtype.Date     `json:"date_of_birth"`
	Gender            pgtype.Text     `json:"gender"`
	Address           pgtype.Text     `json:"address"`
	Email             pgtype.Text     `json:"email"`
	Phone             pgtype.Text     `json:"phone"`
	CccdNumber        pgtype.Text     `json:"cccd_number"`
	AvatarUrl         pgtype.Text     `json:"avatar_url"`
	FaceEmbedding     pgvector.Vector `json:"face_embedding"`
	EmergencyContacts []byte          `json:"emergency_contacts"`
}

func (q *Queries) CreateCitizen(ctx context.Context, arg CreateCitizenParams) (Citizens, error) {
	row := q.db.QueryRow(ctx, createCitizen,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.Email,
		arg.Phone,
		arg.CccdNumber,
		arg.AvatarUrl,
		arg.FaceEmbedding,
		arg.EmergencyContacts,
	)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.CccdNumber,
		&i.AvatarUrl,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmergencyReport = `-- name: CreateEmergencyReport :one
INSERT INTO emergency_reports (
    reporter_id, victim_id, location_lat, location_lon, situation_description
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, reporter_id, victim_id, location_lat, location_lon, situation_description, status, created_at, updated_at
`

type CreateEmergencyReportParams struct {
	ReporterID           pgtype.UUID `json:"reporter_id"`
	VictimID             pgtype.UUID `json:"victim_id"`
	LocationLat          string      `json:"location_lat"`
	LocationLon          string      `json:"location_lon"`
	SituationDescription pgtype.Text `json:"situation_description"`
}

func (q *Queries) CreateEmergencyReport(ctx context.Context, arg CreateEmergencyReportParams) (EmergencyReports, error) {
	row := q.db.QueryRow(ctx, createEmergencyReport,
		arg.ReporterID,
		arg.VictimID,
		arg.LocationLat,
		arg.LocationLon,
		arg.SituationDescription,
	)
	var i EmergencyReports
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.VictimID,
		&i.LocationLat,
		&i.LocationLon,
		&i.SituationDescription,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedicalRecord = `-- name: CreateMedicalRecord :one
INSERT INTO medical_records (
    citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated
`

type CreateMedicalRecordParams struct {
	CitizenID           pgtype.UUID `json:"citizen_id"`
	DistinguishingMarks pgtype.Text `json:"distinguishing_marks"`
	BloodGroup          pgtype.Text `json:"blood_group"`
	Allergies           []string    `json:"allergies"`
	BackgroundDiseases  []string    `json:"background_diseases"`
	CurrentMedications  []string    `json:"current_medications"`
	Notes               pgtype.Text `json:"notes"`
}

func (q *Queries) CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, createMedicalRecord,
		arg.CitizenID,
		arg.DistinguishingMarks,
		arg.BloodGroup,
		arg.Allergies,
		arg.BackgroundDiseases,
		arg.CurrentMedications,
		arg.Notes,
	)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const createQRCode = `-- name: CreateQRCode :one
INSERT INTO qr_codes (
    name, status, citizen_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, status, citizen_id, created_at, last_used_at
`

type CreateQRCodeParams struct {
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	CitizenID pgtype.UUID `json:"citizen_id"`
}

func (q *Queries) CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCodes, error) {
	row := q.db.QueryRow(ctx, createQRCode, arg.Name, arg.Status, arg.CitizenID)
	var i QrCodes
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCitizen = `-- name: GetCitizen :one
SELECT id, full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts, created_at, updated_at FROM citizens
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCitizen(ctx context.Context, id pgtype.UUID) (Citizens, error) {
	row := q.db.QueryRow(ctx, getCitizen, id)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.CccdNumber,
		&i.AvatarUrl,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCitizenByCCCD = `-- name: GetCitizenByCCCD :one
SELECT id, full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts, created_at, updated_at FROM citizens
WHERE cccd_number = $1 LIMIT 1
`

func (q *Queries) GetCitizenByCCCD(ctx context.Context, cccdNumber pgtype.Text) (Citizens, error) {
	row := q.db.QueryRow(ctx, getCitizenByCCCD, cccdNumber)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.CccdNumber,
		&i.AvatarUrl,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyHistory = `-- name: GetEmergencyHistory :many
SELECT id, reporter_id, victim_id, location_lat, location_lon, situation_description, status, created_at, updated_at FROM emergency_reports
WHERE reporter_id = $1 OR victim_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetEmergencyHistory(ctx context.Context, reporterID pgtype.UUID) ([]EmergencyReports, error) {
	rows, err := q.db.Query(ctx, getEmergencyHistory, reporterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmergencyReports
	for rows.Next() {
		var i EmergencyReports
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.VictimID,
			&i.LocationLat,
			&i.LocationLon,
			&i.SituationDescription,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMedicalRecord = `-- name: GetMedicalRecord :one
SELECT citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated FROM medical_records
WHERE citizen_id = $1 LIMIT 1
`

func (q *Queries) GetMedicalRecord(ctx context.Context, citizenID pgtype.UUID) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, getMedicalRecord, citizenID)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const getNFCTag = `-- name: GetNFCTag :one
SELECT id, name, type, status, citizen_id, registered_at, last_used_at FROM nfc_tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNFCTag(ctx context.Context, id string) (NfcTags, error) {
	row := q.db.QueryRow(ctx, getNFCTag, id)
	var i NfcTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CitizenID,
		&i.RegisteredAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getQRCode = `-- name: GetQRCode :one
SELECT id, name, status, citizen_id, created_at, last_used_at FROM qr_codes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQRCode(ctx context.Context, id pgtype.UUID) (QrCodes, error) {
	row := q.db.QueryRow(ctx, getQRCode, id)
	var i QrCodes
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const registerNFCTag = `-- name: RegisterNFCTag :one
INSERT INTO nfc_tags (
    id, name, type, status, citizen_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, type, status, citizen_id, registered_at, last_used_at
`

type RegisterNFCTagParams struct {
	ID        string      `json:"id"`
	Name      pgtype.Text `json:"name"`
	Type      pgtype.Text `json:"type"`
	Status    string      `json:"status"`
	CitizenID pgtype.UUID `json:"citizen_id"`
}

func (q *Queries) RegisterNFCTag(ctx context.Context, arg RegisterNFCTagParams) (NfcTags, error) {
	row := q.db.QueryRow(ctx, registerNFCTag,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.CitizenID,
	)
	var i NfcTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CitizenID,
		&i.RegisteredAt,
		&i.LastUsedAt,
	)
	return i, err
}

const searchCitizenByFace = `-- name: SearchCitizenByFace :many
SELECT id, full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts, created_at, updated_at, (face_embedding <-> $1) AS distance
FROM citizens
ORDER BY distance ASC
LIMIT $2
`

type SearchCitizenByFaceParams struct {
	FaceEmbedding pgvector.Vector `json:"face_embedding"`
	Limit         int32           `json:"limit"`
}

type SearchCitizenByFaceRow struct {
	ID                pgtype.UUID        `json:"id"`
	FullName          string             `json:"full_name"`
	DateOfBirth       pgtype.Date        `json:"date_of_birth"`
	Gender            pgtype.Text        `json:"gender"`
	Address           pgtype.Text        `json:"address"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	CccdNumber        pgtype.Text        `json:"cccd_number"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	FaceEmbedding     pgvector.Vector    `json:"face_embedding"`
	EmergencyContacts []byte             `json:"emergency_contacts"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Distance          interface{}        `json:"distance"`
}

func (q *Queries) SearchCitizenByFace(ctx context.Context, arg SearchCitizenByFaceParams) ([]SearchCitizenByFaceRow, error) {
	rows, err := q.db.Query(ctx, searchCitizenByFace, arg.FaceEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCitizenByFaceRow
	for rows.Next() {
		var i SearchCitizenByFaceRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Address,
			&i.Email,
			&i.Phone,
			&i.CccdNumber,
			&i.AvatarUrl,
			&i.FaceEmbedding,
			&i.EmergencyContacts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCitizen = `-- name: UpdateCitizen :one
UPDATE citizens
SET 
    full_name = COALESCE($2, full_name),
    date_of_birth = COALESCE($3, date_of_birth),
    gender = COALESCE($4, gender),
    address = COALESCE($5, address),
    email = COALESCE($6, email),
    phone = COALESCE($7, phone),
    cccd_number = COALESCE($8, cccd_number),
    avatar_url = COALESCE($9, avatar_url),
    face_embedding = COALESCE($10, face_embedding),
    emergency_contacts = COALESCE($11, emergency_contacts),
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, date_of_birth, gender, address, email, phone, cccd_number, avatar_url, face_embedding, emergency_contacts, created_at, updated_at
`

type UpdateCitizenParams struct {
	ID                pgtype.UUID     `json:"id"`
	FullName          pgtype.Text     `json:"full_name"`
	DateOfBirth       pgtype.Date     `json:"date_of_birth"`
	Gender            pgtype.Text     `json:"gender"`
	Address           pgtype.Text     `json:"address"`
	Email             pgtype.Text     `json:"email"`
	Phone             pgtype.Text     `json:"phone"`
	CccdNumber        pgtype.Text     `json:"cccd_number"`
	AvatarUrl         pgtype.Text     `json:"avatar_url"`
	FaceEmbedding     pgvector.Vector `json:"face_embedding"`
	EmergencyContacts []byte          `json:"emergency_contacts"`
}

func (q *Queries) UpdateCitizen(ctx context.Context, arg UpdateCitizenParams) (Citizens, error) {
	row := q.db.QueryRow(ctx, updateCitizen,
		arg.ID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.Email,
		arg.Phone,
		arg.CccdNumber,
		arg.AvatarUrl,
		arg.FaceEmbedding,
		arg.EmergencyContacts,
	)
	var i Citizens
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.CccdNumber,
		&i.AvatarUrl,
		&i.FaceEmbedding,
		&i.EmergencyContacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMedicalRecord = `-- name: UpdateMedicalRecord :one
UPDATE medical_records
SET
    distinguishing_marks = COALESCE($2, distinguishing_marks),
    blood_group = COALESCE($3, blood_group),
    allergies = COALESCE($4, allergies),
    background_diseases = COALESCE($5, background_diseases),
    current_medications = COALESCE($6, current_medications),
    notes = COALESCE($7, notes),
    last_updated = NOW()
WHERE citizen_id = $1
RETURNING citizen_id, distinguishing_marks, blood_group, allergies, background_diseases, current_medications, notes, last_updated
`

type UpdateMedicalRecordParams struct {
	CitizenID           pgtype.UUID `json:"citizen_id"`
	DistinguishingMarks pgtype.Text `json:"distinguishing_marks"`
	BloodGroup          pgtype.Text `json:"blood_group"`
	Allergies           []string    `json:"allergies"`
	BackgroundDiseases  []string    `json:"background_diseases"`
	CurrentMedications  []string    `json:"current_medications"`
	Notes               pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateMedicalRecord(ctx context.Context, arg UpdateMedicalRecordParams) (MedicalRecords, error) {
	row := q.db.QueryRow(ctx, updateMedicalRecord,
		arg.CitizenID,
		arg.DistinguishingMarks,
		arg.BloodGroup,
		arg.Allergies,
		arg.BackgroundDiseases,
		arg.CurrentMedications,
		arg.Notes,
	)
	var i MedicalRecords
	err := row.Scan(
		&i.CitizenID,
		&i.DistinguishingMarks,
		&i.BloodGroup,
		&i.Allergies,
		&i.BackgroundDiseases,
		&i.CurrentMedications,
		&i.Notes,
		&i.LastUpdated,
	)
	return i, err
}

const updateNFCLastUsed = `-- name: UpdateNFCLastUsed :exec
UPDATE nfc_tags
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateNFCLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateNFCLastUsed, id)
	return err
}

const updateNFCTagStatus = `-- name: UpdateNFCTagStatus :one
UPDATE nfc_tags
SET status = $2
WHERE id = $1
RETURNING id, name, type, status, citizen_id, registered_at, last_used_at
`

type UpdateNFCTagStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNFCTagStatus(ctx context.Context, arg UpdateNFCTagStatusParams) (NfcTags, error) {
	row := q.db.QueryRow(ctx, updateNFCTagStatus, arg.ID, arg.Status)
	var i NfcTags
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.CitizenID,
		&i.RegisteredAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateQRLastUsed = `-- name: UpdateQRLastUsed :exec
UPDATE qr_codes
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateQRLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateQRLastUsed, id)
	return err
}

const updateQRStatus = `-- name: UpdateQRStatus :one
UPDATE qr_codes
SET status = $2
WHERE id = $1
RETURNING id, name, status, citizen_id, created_at, last_used_at
`

type UpdateQRStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateQRStatus(ctx context.Context, arg UpdateQRStatusParams) (QrCodes, error) {
	row := q.db.QueryRow(ctx, updateQRStatus, arg.ID, arg.Status)
	var i QrCodes
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CitizenID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
